### ISSUE TITLE
How to get similarity_Lm3D_all.mat？

### ISSUE THREAD

**Issue by TREASUREPPY** [HUuxiaobin/Face-Super-Resolution-Guided-by-3D-Facial-Priors#3]
Thank you very much for your work. Could you please tell me where I can download the similarity_lm3d_all.mat file? Thank you

**Comment by HUuxiaobin** [comment]
seen in BFM folder

**Comment by TREASUREPPY** [comment]
Thank you. I'm working on your experiment-------- 原始邮件 --------发件人： "Xiaobin HU(kevin)" <notifications@github.com>日期： 2021年2月4日周四 20:02收件人： HUuxiaobin/Face-Super-Resolution-Guided-by-3D-Facial-Priors <Face-Super-Resolution-Guided-by-3D-Facial-Priors@noreply.github.com>抄送： TREASUREPPY <PPY_1203@163.com>, State change <state_change@noreply.github.com>主    题： Re: [HUuxiaobin/Face-Super-Resolution-Guided-by-3D-Facial-Priors] How to get similarity_Lm3D_all.mat？ (#3)
seen in BFM folder
